### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Liming-Cheng** [muskie82/CNN-DSO#3]
Hi @muskie82 ,  I can build dso successfully, but there is a very very confused problem when I build this repo.  

[ 96%] Building CXX object CMakeFiles/dso_dataset.dir/src/main_dso_pangolin.cpp.o
/home/cheng/CNN-DSO/src/main_dso_pangolin.cpp: In function ‘void parseArgument(char*)’:
/home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:222:4: error: reference to ‘reverse’ is ambiguous
    reverse = true;
    ^
/home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:59:6: note: candidates are: bool reverse
 bool reverse = false;
      ^
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /usr/local/include/eigen3/Eigen/Core:297,
                 from /home/cheng/CNN-DSO/src/util/NumType.h:27,
                 from /home/cheng/CNN-DSO/src/IOWrapper/Output3DWrapper.h:30,
                 from /home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:33:
/usr/include/c++/4.8/bits/stl_algo.h:1442:5: note:                 template<class _BIter> void std::reverse(_BIter, _BIter)
     reverse(_BidirectionalIterator __first, _BidirectionalIterator __last)
     ^
/home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:262:3: error: reference to ‘end’ is ambiguous
   end = option;
   ^
/home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:62:5: note: candidates are: int end
 int end=100000;
     ^
In file included from /usr/include/c++/4.8/string:51:0,
                 from /usr/include/c++/4.8/stdexcept:39,
                 from /usr/include/c++/4.8/array:38,
                 from /usr/include/c++/4.8/tuple:39,
                 from /usr/include/c++/4.8/functional:55,
                 from /usr/include/c++/4.8/thread:39,
                 from /home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:26:
/usr/include/c++/4.8/bits/range_access.h:97:5: note:                 template<class _Tp, long unsigned int _Nm> _Tp* std::end(_Tp (&)[_Nm])
     end(_Tp (&__arr)[_Nm])
     ^
/usr/include/c++/4.8/bits/range_access.h:78:5: note:                 template<class _Container> decltype (__cont.end()) std::end(const _Container&)
     end(const _Container& __cont) -> decltype(__cont.end())
     ^
/usr/include/c++/4.8/bits/range_access.h:68:5: note:                 template<class _Container> decltype (__cont.end()) std::end(_Container&)
     end(_Container& __cont) -> decltype(__cont.end())
     ^
In file included from /usr/include/c++/4.8/utility:74:0,
                 from /usr/include/c++/4.8/tuple:38,
                 from /usr/include/c++/4.8/functional:55,
                 from /usr/include/c++/4.8/thread:39,
                 from /home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:26:
/usr/include/c++/4.8/initializer_list:99:5: note:                 template<class _Tp> constexpr const _Tp* std::end(std::initializer_list<_Tp>)
     end(initializer_list<_Tp> __ils) noexcept
     ^
/home/cheng/CNN-DSO/src/main_dso_pangolin.cpp: In function ‘int main(int, char**)’:
/home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:385:13: error: reference to ‘end’ is ambiguous
  int lend = end;
             ^
/home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:62:5: note: candidates are: int end
 int end=100000;
     ^
In file included from /usr/include/c++/4.8/string:51:0,
                 from /usr/include/c++/4.8/stdexcept:39,
                 from /usr/include/c++/4.8/array:38,
                 from /usr/include/c++/4.8/tuple:39,
                 from /usr/include/c++/4.8/functional:55,
                 from /usr/include/c++/4.8/thread:39,
                 from /home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:26:
/usr/include/c++/4.8/bits/range_access.h:97:5: note:                 template<class _Tp, long unsigned int _Nm> _Tp* std::end(_Tp (&)[_Nm])
     end(_Tp (&__arr)[_Nm])
     ^
/usr/include/c++/4.8/bits/range_access.h:78:5: note:                 template<class _Container> decltype (__cont.end()) std::end(const _Container&)
     end(const _Container& __cont) -> decltype(__cont.end())
     ^
/usr/include/c++/4.8/bits/range_access.h:68:5: note:                 template<class _Container> decltype (__cont.end()) std::end(_Container&)
     end(_Container& __cont) -> decltype(__cont.end())
     ^
In file included from /usr/include/c++/4.8/utility:74:0,
                 from /usr/include/c++/4.8/tuple:38,
                 from /usr/include/c++/4.8/functional:55,
                 from /usr/include/c++/4.8/thread:39,
                 from /home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:26:
/usr/include/c++/4.8/initializer_list:99:5: note:                 template<class _Tp> constexpr const _Tp* std::end(std::initializer_list<_Tp>)
     end(initializer_list<_Tp> __ils) noexcept
     ^
/home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:387:5: error: reference to ‘reverse’ is ambiguous
  if(reverse)
     ^
/home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:59:6: note: candidates are: bool reverse
 bool reverse = false;
      ^
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /usr/local/include/eigen3/Eigen/Core:297,
                 from /home/cheng/CNN-DSO/src/util/NumType.h:27,
                 from /home/cheng/CNN-DSO/src/IOWrapper/Output3DWrapper.h:30,
                 from /home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:33:
/usr/include/c++/4.8/bits/stl_algo.h:1442:5: note:                 template<class _BIter> void std::reverse(_BIter, _BIter)
     reverse(_BidirectionalIterator __first, _BidirectionalIterator __last)
     ^
/home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:390:10: error: reference to ‘end’ is ambiguous
   lstart=end-1;
          ^
/home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:62:5: note: candidates are: int end
 int end=100000;
     ^
In file included from /usr/include/c++/4.8/string:51:0,
                 from /usr/include/c++/4.8/stdexcept:39,
                 from /usr/include/c++/4.8/array:38,
                 from /usr/include/c++/4.8/tuple:39,
                 from /usr/include/c++/4.8/functional:55,
                 from /usr/include/c++/4.8/thread:39,
                 from /home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:26:
/usr/include/c++/4.8/bits/range_access.h:97:5: note:                 template<class _Tp, long unsigned int _Nm> _Tp* std::end(_Tp (&)[_Nm])
     end(_Tp (&__arr)[_Nm])
     ^
/usr/include/c++/4.8/bits/range_access.h:78:5: note:                 template<class _Container> decltype (__cont.end()) std::end(const _Container&)
     end(const _Container& __cont) -> decltype(__cont.end())
     ^
/usr/include/c++/4.8/bits/range_access.h:68:5: note:                 template<class _Container> decltype (__cont.end()) std::end(_Container&)
     end(_Container& __cont) -> decltype(__cont.end())
     ^
In file included from /usr/include/c++/4.8/utility:74:0,
                 from /usr/include/c++/4.8/tuple:38,
                 from /usr/include/c++/4.8/functional:55,
                 from /usr/include/c++/4.8/thread:39,
                 from /home/cheng/CNN-DSO/src/main_dso_pangolin.cpp:26:
/usr/include/c++/4.8/initializer_list:99:5: note:                 template<class _Tp> constexpr const _Tp* std::end(std::initializer_list<_Tp>)
     end(initializer_list<_Tp> __ils) noexcept
     ^
CMakeFiles/dso_dataset.dir/build.make:62: recipe for target 'CMakeFiles/dso_dataset.dir/src/main_dso_pangolin.cpp.o' failed
make[2]: *** [CMakeFiles/dso_dataset.dir/src/main_dso_pangolin.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dso_dataset.dir/all' failed
make[1]: *** [CMakeFiles/dso_dataset.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I found using g++5 and g++6 caused same error, so I guess it's due to enviroment configuration for CNN or others.  What are the versions of your tensorflow, cuda, cudnn, gcc and  opencv ? Could you give me some suggestions? Looking forward to your reply ! Thank you very much!

**Comment by GentlemanCheng** [comment]
Hi, I found that using c++ 5 has same problem, so I have no idea now, looking forward to your reply! Thank you very much! @muskie82

**Comment by GentlemanCheng** [comment]
Hi @muskie82 , could you tell me your configuration for this work (as mentioned above) when you are not busy? Thank you !

**Comment by zsustc** [comment]
Compiler can't differentiate between the variable "end" and std::end after you introduced the entire std namespace into the current (global) scope using the using namespace std;. Avoid using using namespace std;.
So, change "end" with another name, such as "num_end"
